<div class="container-fluid">
    <div class="block-header">
        <h2>工具 > 自动删除数据</h2>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="header">
                    <h2>自动删除数据</h2> 
                    <br>
                    <small>建议在应用任何操作之前创建备份。</small>
                </div>
                <div class="body">
                   <label for="delete">选择要删除的内容</label>
                        <select class="form-control show-tick" id="delete" name="delete">
                           <option value="1">删除所有非活跃用户</option>
                           <option value="2">删除未登录超过1周的用户</option>
                           <option value="3">删除未登录超过1个月的用户</option>
                           <option value="4">删除未登录超过1年的用户</option>
                           <option value="5">删除超过1周的文章</option>
                           <option value="6">删除超过1个月的文章</option>
                           <option value="7">删除超过1一年的文章</option>
                        </select>
                        <div class="clearfix"></div><br>
                        <small>此过程可能需要一些时间，您可以在几分钟后检查您的网站更改.</small><br>
                  <button type="submit" class="btn btn-danger waves-effect waves-light m-t-20" id="delete-btn">删除数据</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
<script>
$(document).on('click', '#delete-btn', function(event) {
	event.preventDefault();
	if (!confirm('你确定你要删除？ 这个动作无法撤消')) {
		return false;
	}
	$(this).text('请稍后..');
	$.get(Wo_Ajax_Requests_File(), {f:'admin_setting', s: 'auto_delete', delete: $('#delete').val()}, function(data, textStatus, xhr) {
		$('#delete-btn').text('数据正在删除，几分钟后检查您的网站.');
		setTimeout(function () {
			$('#delete-btn').text('删除数据');
		}, 4000);
	});
});
</script>