<?php 
$colors = $db->get(T_COLORS);
 ?>
<div class="container-fluid">
    <div class="block-header">
        <h2>设置 > 贴文设置 > 管理彩色贴文</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
		<div class="col-md-1"></div>
        <div class="col-md-5">
            <div class="card">
                <div class="header">
                    <h2>添加彩色贴文</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success add-provider-settings-alert"></div>
                    <form class="add-provider-settings" method="POST">
						<div class="row">
							<div class="col-md-6">
							<div class="form-group form-float">
								<div class="form-line">
									<input type="color" id="color_1" name="color_1" class="form-control" onchange="change_color()" value="#ffb0ff">
									<label class="form-label">颜色 1</label>
								</div>
							</div>
							</div>
							<div class="col-md-6">
							<div class="form-group form-float">
								<div class="form-line">
									<input type="color" id="color_2" name="color_2" class="form-control" onchange="change_color()" value="#8080c0">
									<label class="form-label">颜色 2</label>
								</div>
							</div>
							</div>
						</div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="color" id="color_text" name="color_text" class="form-control" onchange="change_color()" value="#000">
                                <label class="form-label">文本颜色</label>
                            </div>
                        </div>
                        <div style="height: 300px;width: 100%" id="color_preview">
                            <h2 style="text-align: center;padding-top: 140px" id="text_color">松果生成 !!</h2>
                        </div>
                        <div class="clearfix"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">添加</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card">
                <div class="header">
                    <h2>添加图片贴文</h2>
                </div>
                <div class="body">
                    <div class="alert alert-success add-image-settings-alert"></div>
                    <div class="alert alert-danger add-image-settings-alert-danger"></div>
                    <form class="add-image-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="file" id="image_" name="image" class="form-control" onchange="change_image()">
                            </div>
                        </div>
						<br>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="color" id="image_color" name="image_color" class="form-control" onchange="change_image()" value="#000000">
                                <label class="form-label">文本颜色</label>
                            </div>
                        </div>
                        <div style="height: 300px;width: 100%;background-position: center;background-repeat: no-repeat;background-size: cover;" id="image_preview">
                            <h2 style="text-align: center;padding-top: 140px" id="image_text_color">松果商城 !!</h2>
                        </div>
                        <div class="clearfix"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">添加</button>
                    </form>
                </div>
            </div>
        </div>
		<div class="col-md-1"></div>
	</div>
	<div class="row">
		<?php foreach ($colors as $key => $color) { ?>
			<?php if (!empty($color->color_1) && !empty($color->color_2) && !empty($color->text_color)) { ?>
				<div class="col-md-3" id="list_<?php echo $color->id; ?>">
					<div class="wo_colrd_post_sample" style="background-image: linear-gradient(45deg, <?php echo $color->color_1; ?> 0%, <?php echo $color->color_2; ?> 100%)">
						<span onclick="DeleteColorById(<?php echo $color->id; ?>)"><i class="material-icons">close</i></span>
						<h3 style="color: <?php echo $color->text_color; ?>">松果商城 !!</h3>
					</div>
				</div>
			<?php }elseif (!empty($color->image) && !empty($color->text_color)) { ?>
				<div class="col-md-3" id="list_<?php echo $color->id; ?>">
					<div class="wo_colrd_post_sample" style="background-image:url('<?php echo Wo_GetMedia($color->image); ?>');">
						<span onclick="DeleteColorById(<?php echo $color->id; ?>)"><i class="material-icons">close</i></span>
						<h3 style="color: <?php echo $color->text_color; ?>">松果商城 !!</h3>
					</div>
				</div>
			<?php } ?>
		<?php } ?>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
    c1 = $('#color_1').val();
    c2 = $('#color_2').val();
    tc = $('#color_text').val();
    itc = $('#image_color').val();
    $('#color_preview').css({'background-image':'linear-gradient(45deg, '+c1+' 0%, '+c2+' 100%)' });
    $('#text_color').css({'color': tc });
    $('#image_text_color').css({'color': itc });

    function change_color() {
        c1 = $('#color_1').val();
        c2 = $('#color_2').val();
        tc = $('#color_text').val();
        $('#color_preview').css({'background-image':'linear-gradient(45deg, '+c1+' 0%, '+c2+' 100%)' });
        $('#text_color').css({'color': tc });
    }
    function change_image() {
        console.log($('#image_')[0].files[0])
        itc = $('#image_color').val();
        $('#image_preview').css({'background-image':'url('+window.URL.createObjectURL($('#image_')[0].files[0])+')' });
        $('#image_text_color').css({'color': itc });
    }

    function DeleteColorById(id) {
        if (confirm("Are you sure you want to delete this color?") == false) {
            return false;
        }
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_color', {id: id}, function(data, textStatus, xhr) {
            $('#list_'+id).remove();
        });
    }


    $(function () {

        var form_add_site_settings = $('form.add-provider-settings');
        form_add_site_settings.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_color',
            beforeSend: function() {
                form_add_site_settings.find('.waves-effect').text('Please wait..');
            },
            success: function(data) {
                if (data.status == 200) {
                    form_add_site_settings.find('.waves-effect').text('Add');
                    $("html, body").animate({ scrollTop: 0 }, "slow");
                    $('.add-provider-settings-alert').html('<i class="fa fa-check"></i> Color successfully added');
                    setTimeout(function () {
                        $('.add-provider-settings-alert').empty();
                        location.reload();
                    }, 2000);
                }
            }
        });


        var form_add_image_settings = $('form.add-image-settings');
        form_add_image_settings.ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_image_post',
            beforeSend: function() {
                form_add_image_settings.find('.waves-effect').text('Please wait..');
            },
            success: function(data) {
                if (data.status == 200) {
                    form_add_image_settings.find('.waves-effect').text('Add');
                    $("html, body").animate({ scrollTop: 0 }, "slow");
                    $('.add-image-settings-alert').html('<i class="fa fa-check"></i> Image successfully added');
                    setTimeout(function () {
                        $('.add-image-settings-alert').empty();
                        location.reload();
                    }, 2000);
                }
                else{
                    form_add_image_settings.find('.waves-effect').text('Add');
                    $('.add-image-settings-alert-danger').html(data.error);
                    setTimeout(function () {
                        $('.add-image-settings-alert-danger').empty();
                    }, 2000);
                }
            }
        });

        
    });
</script>