<?php 
$message_count = Wo_CountMessages(array('new' => true,'user_id' => $wo['chatList']['user_id']));    
?>
<div class="recipient-chat-user" id ="online_<?php echo $wo['chatList']['user_id'];?>" >
   <div class="user-info" onclick="Wo_OpenChatTab(<?php echo $wo['chatList']['user_id'];?>);">
      <div  class=" <?php echo Wo_RightToLeft('pull-right');?>  " style="margin-right:15px; margin-top:5px;">
         <span class="new-message-alert <?php echo ($message_count == 0) ? 'hidden' : ''; ?>">
         <?php echo $message_count; ?>
         </span>
         <span class="chat-loading-icon"></span>
      </div>

      <?php if($wo['config']['user_lastseen'] == 1 && $wo['chatList']['showlastseen'] != 0) { ?>
      <div class="user-lastseen" >
         <?php echo Wo_UserStatus($wo['chatList']['user_id'],$wo['chatList']['lastseen']); ?>
      </div>
      <?php } ?>
   </div>
</div>
<div class="clear"></div>