<tr id="list-<?php echo($wo['category_lang_key']) ?>">
  <td><?php echo($wo['category_key']) ?></td>
  <td id="sub_name_<?php echo($wo['category_key']) ?>"><?php echo($wo['category_name']) ?></td>
  <td>
  	<button class="btn bg-cyan waves-effect waves-light"onclick="edit_category('<?php echo($wo['category_lang_key']) ?>')">编辑</button>
  	<?php if ($wo['category_lang_key'] != 'all_') { ?>
  		<button class="btn btn-danger waves-effect waves-light delete-content" data-id="<?php echo($wo['category_lang_key']) ?>">删除</button>
  	<?php } ?>
  </td>
</tr>